const Strings = {
    app_name: "TabRedux Demo",
    no_internet: "No Internet Connection",
    title_time_out: "Request time out",
    title_loading: "Loading...",
    title_permission_denied: "Permission Denied",
    title_wait: "Please wait...",
    title_cancel: "Cancel",
    title_menu: "Menu",
    title_ok: "Ok",
    title_done: "Done",
    title_save: "Save",
    title_select: "Select",
    title: "Title",
    message_saved_successfully: "Saved Successfully",
    message_updated_successfully: "Updated Successfully",
    message_deleted_successfully: "Deleted Successfully",
    message_no_data_found: "No Data Found",
    message_failed: "Ops,Something went wrong!",
    title_not_available: "Not Available",
    title_add: "Add",
    title_delete: "Delete",
    title_update: "Update",
    placeholder_email: "Email Adderess",
    placeholder_password: "Password",
    title_submit: "Submit",
    title_confirm: "Confirm",
    title_logout: "Logout",
    title_login: "Login",
};
export default Strings;